import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import './globals.css'
import { CartProvider } from '@/hooks/useCart'
import Header from '@/components/Header'
import AsideBar from '@/components/AsideBar'

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
})

export const metadata: Metadata = {
  title: 'Ignite Shop',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <CartProvider>
          <div className="relative flex flex-col items-start justify-center h-screen">
            <AsideBar />
            <Header />
            {children}
          </div>
        </CartProvider>
      </body>
    </html>
  )
}
