import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import './globals.css'
import Image from 'next/image'
import LogoImg from '../assets/logoImg.svg'
import Link from 'next/link'
import { PiHandbag } from 'react-icons/pi'
import { CartProvider } from '@/hooks/useCart'

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
})

export const metadata: Metadata = {
  title: 'Ignite Shop',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <CartProvider>
          <div className="flex flex-col items-start justify-center h-screen">
            <header className="w-full py-[2rem] max-w-[1180px] mx-auto flex items-center justify-between">
              <Link href="/">
                <Image src={LogoImg} alt="" />
              </Link>

              <div className="relative bg-[#202024] p-3 rounded-lg">
                <PiHandbag size={30} />
              </div>
            </header>
            {children}
          </div>
        </CartProvider>
      </body>
    </html>
  )
}
